layout_spectrum: 0.07935507
typography_spectrum: 0.1778011
color:
  saturation: 0.31289
  lightness: 0.617895
  brandStrength: 0.2240852
  rhythmicContrast: 0.6173403
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: ETTUTEXAS
